services:
  image-s3-api:
    container_name: image-s3-api
    build: .
    environment:
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_REGION: ${R2_REGION}
    ports:
      - "8803:8803"